### ISSUE TITLE
lfmComputeUpsilonMatrix not compiled for Mac OS X

### ISSUE THREAD

**Issue by wil-j-wil** [SheffieldML/GPmat#11]
Hi,

I am trying to run your Latent Force Model scripts on my Mac but the mex files in kern/mex/ are not recognised because they were compiled for Windows.

So when I run lfmSample.m i get the following error:
"Undefined function or variable 'lfmComputeUpsilonMatrix'."

I am struggling to recompile the Fortran files myself (I have tried for a while) - are you able to compile them for OS X, or could they be re-written as m files?

Thanks

**Comment by lawrennd** [comment]
Hi,

Yes, this is an annoying problem. I've also got OSX and have struggled to
compile them, I normally use a surface book if I need to run those demos.

The m files (unfortunately) would be extremely slow because the Fadeeva
function is missing from MATLAB (or at least it was). Obviously if you are
able to make any progress with this issue we would welcome a pull request.

Neil
